### PR TITLE
Justin segler experience report

### PR DESCRIPTION
**Pull request by justin-segler**

### CODE REVIEW

**Comment by jameshowison** [comment]
Hi Justin,

I'll grade the report as on time, but you've included two .DS_Store files in this pull request.  Could you create a clean PR without those please?

**Comment by justin-segler** [comment]
As apart of my pull request, I actually have a commit that removes those two files.

**Comment by jameshowison** [comment]
Hmmm, you are right, I see the deletions. Thing is that I'm getting a "Conflicting files" on assignment_submission/.DS_Store .  Might be an interaction with other students, I'll resolve it manually and accept.

**Comment by justin-segler** [comment]
Thank you! Sorry about that…

**Comment by jameshowison** [comment]
No worries, we should have .DS_Store files in .gitignore anyway :)

**Pull request merged**
