### PR TITLE
This is a draft

### PR DESCRIPTION
**Pull request by Joohee09**

### CODE REVIEW

**Comment by jameshowison** [comment]
Looks good.  Could you describe more about how you felt? Did you feel engaged? Motivated? Could you relate your experience to more of the literature?  Also use the citations part of Rmarkdown https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html (Export the .bib file from Zotero and include it in the pull request.

Great to see that you used a branch for this submission :)

**Comment by Joohee09** [comment]
> Looks good. Could you describe more about how you felt? Did you feel engaged? Motivated? Could you relate your experience to more of the literature? Also use the citations part of Rmarkdown https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html (Export the .bib file from Zotero and include it in the pull request.
> 
> Great to see that you used a branch for this submission :)

**Comment by Joohee09** [comment]
Thank you for taking the time to give me feedback!
I will add more motivation and work on the citation. 

Can we write over 500 words? Now mine is over 700 words and I need to add
motivations and citations adjusting previous writing.

**Comment by jameshowison** [comment]
Yes, 700 words is ok, can also use tables.

**Pull request closed without merging**
