### PR TITLE
Tina Lassiter - Slides for the Presentation

### PR DESCRIPTION
**Pull request by TinaLas**

### CODE REVIEW

**Comment by jameshowison** [comment]
Please make this pull request just the report, so take the slides out of this one?

**Comment by TinaLas** [comment]
How do I do that? I was actually surprised that the other commits showed up again in this pull request. I thought I had just committed the slides to this one.

Here is my Terminal history:

475  cd peer_production_course
  476  git checkout -b PP_Lassiter_BookCrossing-Slides
  477  git status
  478  git add assignment_submission/experience_slides/PP_Lassiter_BookCrossing-Slides.Rmd
  479  git commit -m"My submission for the presentation"
  480  git push --set-upstream origin PP_Lassiter_BookCrossing-Slides
  481  history
  482  cd peer_production_course
  483  ls
  484  pwd
  485  cd ..
  486  cd peer_production-course
  487  cd peer_production_course
  488  cd assignment_submission/experience_slides
  489  ls
  490  ls PP_Lassiter_BookCrossing-Slides_files
  491  git add PP_Lassiter_BookCrossing-Slides_files
  492  git commit -m"Adding my image files"
  493  git push

**Comment by TinaLas** [comment]
So I guess I did not manage to get the other commits out of the Slides branch yesterday. I now tried again to delete the commits from the branch. Does this work?

**Comment by jameshowison** [comment]
Well done, looks like you sorted that out.  I think the trouble was that the branch you made for the slides already had the report in it?

**Pull request merged**
