### PR TITLE
Experience Paper Draft

### PR DESCRIPTION
**Pull request by brwheeler**
Hello! Here's my draft for feedback. I still need to format the citations in Markdown, but they are there manually for now.

### CODE REVIEW

**Comment by jameshowison** [comment]
Great stuff.  These headers worked for me with the citations.  I exported from Zotero to make the example-library.bib file (and put it in the same folder as the Rmd file).

```
title: "TestingCitations"
output: pdf_document
bibliography: example-library.bib
link-citations: true
linkcolor: blue
```

**Comment by jameshowison** [comment]
It would be good to comment on how each of these processes made you feel.  Sounds like there were some delays that can sap motivation as well.

**Comment by brwheeler** [comment]
I added a bit more about motivations. I also tried to link a Bib file to the Rmd file, yet my R Studio is still having troubles. I can't run it as a PDF because I get error messages about not having `LaTex`, and even when I downloaded the `latexpdf` package, the same error message remained. In addition, when I tried to add `link-citations` and `linkcolor`, I got an error message about issues with the YAML and `knitr` refused to generate anything. If you have any more suggestions about how to trouble shoot this issue, let me know. If we can't figure it out, I'll just do it manually and resubmit.

**Comment by jameshowison** [comment]
I grabbed this and got it running on my laptop.  You need to have your in-text citations be like `[@wickham_r_2015]` rather than (Wickham, 2015).  Then knitr sees the [@wickham_r_2015] code and creates the right in-text citation, links it to the 

btw, make sure you pull request from a feature branch not from master.

**Comment by brwheeler** [comment]
Okay! The in-text citations have been fixed, and R Studio finally decided to put my references at the end of my document! 

Every time I push up to my fork, it automatically adds it to this pull request. I think I need to close the pull request to make a new one. Otherwise, everything works. I have no clue what happened to the commit message, but I'm just excited that R Studio is working with me here.

Thank you for taking the time to give me feedback and for helping me with this issue! I greatly appreciate it!!

**Comment by jameshowison** [comment]
Woohoo!

**Pull request closed without merging**
